version: '2'
services:
  web: &web
    build: .
    command: bash -c "bundle && rails s -p 3000 -b '0.0.0.0'"
    # allows connecting to binding.pry using `docker attach ...`
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
